// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tfaas.proto

/*
Package tfaas is a generated protocol buffer package.

It is generated from these files:
	tfaas.proto

It has these top-level messages:
	Data
	PhysicsObjects
*/
package tfaaspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	Name  string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Array []float32 `protobuf:"fixed32,2,rep,packed,name=array" json:"array,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Data) GetArray() []float32 {
	if m != nil {
		return m.Array
	}
	return nil
}

type PhysicsObjects struct {
	Data []*Data `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *PhysicsObjects) Reset()                    { *m = PhysicsObjects{} }
func (m *PhysicsObjects) String() string            { return proto.CompactTextString(m) }
func (*PhysicsObjects) ProtoMessage()               {}
func (*PhysicsObjects) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PhysicsObjects) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "tfaas.Data")
	proto.RegisterType((*PhysicsObjects)(nil), "tfaas.PhysicsObjects")
}

func init() { proto.RegisterFile("tfaas.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x49, 0x4b, 0x4c,
	0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x0c, 0xb8, 0x58, 0x5c,
	0x12, 0x4b, 0x12, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0xc4, 0xa2, 0xa2, 0xc4, 0x4a, 0x09, 0x26, 0x05,
	0x66, 0x0d, 0xa6, 0x20, 0x08, 0x47, 0xc9, 0x90, 0x8b, 0x2f, 0x20, 0xa3, 0xb2, 0x38, 0x33, 0xb9,
	0xd8, 0x3f, 0x29, 0x2b, 0x35, 0xb9, 0xa4, 0x58, 0x48, 0x9e, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x51,
	0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x5b, 0x0f, 0x62, 0x0d, 0xc8, 0xd8, 0x20, 0xb0, 0x44,
	0x12, 0x1b, 0xd8, 0x4a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x50, 0xd9, 0xe5, 0x81,
	0x00, 0x00, 0x00,
}
