// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tfaas.proto

/*
Package tfaaspb is a generated protocol buffer package.

It is generated from these files:
	tfaas.proto

It has these top-level messages:
	Detector
	Hits
	Row
	DataFrame
	Class
	Predictions
*/
package tfaaspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Detector represents a CMS detector with name and x,y,z coordinates
type Detector struct {
	Name string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	X    []float32 `protobuf:"fixed32,2,rep,packed,name=x" json:"x,omitempty"`
	Y    []float32 `protobuf:"fixed32,3,rep,packed,name=y" json:"y,omitempty"`
	Z    []float32 `protobuf:"fixed32,4,rep,packed,name=z" json:"z,omitempty"`
}

func (m *Detector) Reset()                    { *m = Detector{} }
func (m *Detector) String() string            { return proto.CompactTextString(m) }
func (*Detector) ProtoMessage()               {}
func (*Detector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Detector) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Detector) GetX() []float32 {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Detector) GetY() []float32 {
	if m != nil {
		return m.Y
	}
	return nil
}

func (m *Detector) GetZ() []float32 {
	if m != nil {
		return m.Z
	}
	return nil
}

// Hits is a collection of detector elements
type Hits struct {
	Det []*Detector `protobuf:"bytes,1,rep,name=det" json:"det,omitempty"`
}

func (m *Hits) Reset()                    { *m = Hits{} }
func (m *Hits) String() string            { return proto.CompactTextString(m) }
func (*Hits) ProtoMessage()               {}
func (*Hits) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Hits) GetDet() []*Detector {
	if m != nil {
		return m.Det
	}
	return nil
}

// Row is a collection of keys and values
type Row struct {
	Key   []string  `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	Value []float32 `protobuf:"fixed32,2,rep,packed,name=value" json:"value,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Row) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Row) GetValue() []float32 {
	if m != nil {
		return m.Value
	}
	return nil
}

// DataFrame is a collection of rows
type DataFrame struct {
	Row []*Row `protobuf:"bytes,1,rep,name=row" json:"row,omitempty"`
}

func (m *DataFrame) Reset()                    { *m = DataFrame{} }
func (m *DataFrame) String() string            { return proto.CompactTextString(m) }
func (*DataFrame) ProtoMessage()               {}
func (*DataFrame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DataFrame) GetRow() []*Row {
	if m != nil {
		return m.Row
	}
	return nil
}

// Class represents response from the server, it contains class label name and probability
type Class struct {
	Label       string  `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Probability float32 `protobuf:"fixed32,2,opt,name=probability" json:"probability,omitempty"`
}

func (m *Class) Reset()                    { *m = Class{} }
func (m *Class) String() string            { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()               {}
func (*Class) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Class) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Class) GetProbability() float32 {
	if m != nil {
		return m.Probability
	}
	return 0
}

// Predictions is collection of class probabilities
type Predictions struct {
	Prediction []*Class `protobuf:"bytes,1,rep,name=prediction" json:"prediction,omitempty"`
}

func (m *Predictions) Reset()                    { *m = Predictions{} }
func (m *Predictions) String() string            { return proto.CompactTextString(m) }
func (*Predictions) ProtoMessage()               {}
func (*Predictions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Predictions) GetPrediction() []*Class {
	if m != nil {
		return m.Prediction
	}
	return nil
}

func init() {
	proto.RegisterType((*Detector)(nil), "tfaaspb.Detector")
	proto.RegisterType((*Hits)(nil), "tfaaspb.Hits")
	proto.RegisterType((*Row)(nil), "tfaaspb.Row")
	proto.RegisterType((*DataFrame)(nil), "tfaaspb.DataFrame")
	proto.RegisterType((*Class)(nil), "tfaaspb.Class")
	proto.RegisterType((*Predictions)(nil), "tfaaspb.Predictions")
}

func init() { proto.RegisterFile("tfaas.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4f, 0xc3, 0x20,
	0x18, 0x86, 0x43, 0xd9, 0xd4, 0x7e, 0x5d, 0x8c, 0x12, 0x0f, 0x9c, 0x0c, 0xc1, 0x4b, 0x93, 0xc5,
	0x1e, 0xf4, 0x6c, 0x3c, 0xb8, 0x98, 0x1d, 0x0d, 0xff, 0x00, 0x36, 0x4c, 0x88, 0x38, 0x1a, 0x40,
	0xbb, 0xee, 0xd7, 0x1b, 0x28, 0x36, 0xbb, 0x7d, 0x0f, 0xef, 0x1b, 0x1e, 0xf8, 0xa0, 0x89, 0x9f,
	0x52, 0x86, 0xae, 0xf7, 0x2e, 0x3a, 0x72, 0x99, 0xa1, 0x57, 0x7c, 0x0b, 0x57, 0x1b, 0x1d, 0xf5,
	0x2e, 0x3a, 0x4f, 0x08, 0x2c, 0x0e, 0xf2, 0x5b, 0x53, 0xc4, 0x50, 0x5b, 0x8b, 0x3c, 0x93, 0x15,
	0xa0, 0x23, 0xad, 0x18, 0x6e, 0x2b, 0x81, 0x8e, 0x89, 0x46, 0x8a, 0x27, 0x1a, 0x13, 0x9d, 0xe8,
	0x62, 0xa2, 0x13, 0x5f, 0xc3, 0x62, 0x6b, 0x62, 0x20, 0x0f, 0x80, 0xf7, 0x3a, 0x52, 0xc4, 0x70,
	0xdb, 0x3c, 0xdd, 0x76, 0x45, 0xd4, 0xfd, 0x5b, 0x44, 0x4a, 0xf9, 0x23, 0x60, 0xe1, 0x06, 0x72,
	0x03, 0xf8, 0x4b, 0x8f, 0xb9, 0x5b, 0x8b, 0x34, 0x92, 0x3b, 0x58, 0xfe, 0x4a, 0xfb, 0xa3, 0x8b,
	0x73, 0x02, 0xbe, 0x86, 0x7a, 0x23, 0xa3, 0x7c, 0xf7, 0xe9, 0x49, 0xf7, 0x80, 0xbd, 0x1b, 0x8a,
	0x60, 0x35, 0x0b, 0x84, 0x1b, 0x44, 0x0a, 0xf8, 0x2b, 0x2c, 0xdf, 0xac, 0x0c, 0x21, 0xdd, 0x65,
	0xa5, 0xd2, 0xb6, 0x7c, 0x68, 0x02, 0xc2, 0xa0, 0xe9, 0xbd, 0x53, 0x52, 0x19, 0x6b, 0xe2, 0x48,
	0x2b, 0x86, 0xda, 0x4a, 0x9c, 0x1f, 0xf1, 0x17, 0x68, 0x3e, 0xbc, 0xde, 0x9b, 0x5d, 0x34, 0xee,
	0x10, 0x48, 0x07, 0xd0, 0xcf, 0x58, 0xb4, 0xd7, 0xb3, 0x36, 0xab, 0xc4, 0x59, 0x43, 0x5d, 0xe4,
	0x15, 0x3f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x71, 0xce, 0x9e, 0x14, 0x71, 0x01, 0x00, 0x00,
}
